mutation createRun(
  $startDate: String!
  $endDate: String!
  $startTime: String!
  $endTime: String!
  $intensityFB: Int!
) {
  createRun(
    startDate: $startDate
    endDate: $endDate
    startTime: $startTime
    endTime: $endTime
    intensity: $intensityFB
  ) {
    userId
    date
    duration
    heartRate
    vo2max
    intensityFeedback
  }
}

mutation resyncRun(
  $startDate: String!
  $startTime: String!
  $duration: Int!
  $intensityFeedback: Int!
) {
  resyncRun(
    startDate: $startDate
    startTime: $startTime
    duration: $duration
    intensity: $intensityFeedback
  ) {
    userId
    date
    duration
    heartRate
    vo2max
    intensityFeedback
  }
}
