query MostRecentSleep($sourceUrl: String) {
  currentUser {
    id
    todaysSleep(sourceUrl: $sourceUrl) {
      awake
      rem
      light
      deep
      awakenings
      score
      date
      variables {
        name
        emoji
        custom
      }
      tomorrow
      yesterday
    }
  }
}

query CustomSleepVariables {
  currentUser {
    id
    sleepVariables {
      name
      emoji
      custom
    }
  }
}

mutation AddSleepVariable(
  $name: String!
  $emoji: String!
  $sleepDate: String!
  $custom: Boolean!
) {
  addSleepVariable(
    custom: $custom
    emoji: $emoji
    name: $name
    sleepDate: $sleepDate
  ) {
    date
    variables {
      name
      emoji
      custom
    }
  }
}

mutation RemoveSleepVariable($name: String!, $sleepDate: String!) {
  removeSleepVariable(name: $name, sleepDate: $sleepDate) {
    date
    variables {
      name
      emoji
      custom
    }
  }
}

query AnalyzeSleep {
  analyzeSleep
}
