query CurrentUser {
  currentUser {
    id
    firstName
    lastName
    experience
    stage
    maxHr
    dob
  }
}

mutation CompleteOnboarding(
  $firstName: String!
  $lastName: String!
  $experience: ExperienceLevel!
  $dob: String!
) {
  completeOnboarding(
    experience: $experience
    firstName: $firstName
    lastName: $lastName
    dob: $dob
  ) {
    id
  }
}
