query CurrentUser {
  currentUser {
    id
    firstName
    lastName
    experience
    stage
    maxHr
    dob
    defaultRunDuration
    createdAtUTS
    avatarUrl
    createdAtUTS
    xp
  }
}

query FeaturesSeen {
  currentUser {
    id
    features
  }
}

mutation UpdateDefaultRunDuration($duration: Int!) {
  updateDefaultRunDuration(duration: $duration)
}

mutation MarkFeatureSeen($feature: String!) {
  markFeatureSeen(feature: $feature)
}

mutation CompleteOnboarding(
  $firstName: String!
  $lastName: String!
  $experience: ExperienceLevel!
  $dob: String!
) {
  completeOnboarding(
    experience: $experience
    firstName: $firstName
    lastName: $lastName
    dob: $dob
  ) {
    id
    firstName
    lastName
    experience
    stage
    dob
  }
}

mutation UpdateProfile($firstName: String!, $lastName: String!, $dob: String!) {
  updateProfile(dob: $dob, firstName: $firstName, lastName: $lastName) {
    firstName
    lastName
    dob
  }
}
